layout_spectrum: 1
typography_spectrum: 0.6702509
color:
  saturation: 0.7132391
  lightness: 0.08682736
  brandStrength: 0.9279726
  rhythmicContrast: 0.8342366
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: ryanlee
