name: ryanlee
favicon: null
layout_spectrum: 0.39726
typography_spectrum: 0.38943
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfb'
    - '#333333'
    - '#8b8b8b'
    - '#606060'
    - '#c2c2c2'
  brandStrength: 0.875
  lightness: 0.08682736
  saturation: 0.7132391
  rhythmicContrast: 0.8342366
purpose: []
